### PR TITLE
Solves proxy issue, closes #74 when proxy is set at .profile

### LINKED ISSUE #74: Add support for http_proxy at remote server
My remote server needs to use an http_proxy/https_proxy to download packages from internet. Can you add support for this? Usually I would add `export http_proxy=someproxy:port` and `export https_proxy=someproxy:port` to the beginning of my script.

Even better, can we have an option to run some commands (like the `export`s above) before sshcode starts executing?

### PR DESCRIPTION
**Pull request by eargollo**

### CODE REVIEW

**Comment by eargollo** [comment]
Weird. This is my .gitconfig:
```
$ cat ~/.gitconfig
[core]
        autocrlf = false
        eol = lf
[user]
        name = Eduardo Argollo
        email = eduardo@hp.com
[alias]
        aliases = config --get-regexp alias
        s = status -s
        psu = push --set-upstream
        lg=log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
```

What should I do? Create another branch, push the code again and do a new PR?

Thanks.

**Comment by deansheather** [comment]
You can amend the commit and then force push to your branch.

**Comment by eargollo** [comment]
Just did that. 

```
$ git commit --amend --author="Eduardo Argollo <eduardo@argollo.com>"
$ git push -u proxy-support -f
```

Let me know if that worked out.

Tks

**Comment by deansheather** [comment]
Just needs to be signed with PGP now. You can amend and sign with `git commit --amend -S` once you've setup a PGP key and added it to your GitHub account.

**Comment by eargollo** [comment]
Done. First time I use gpg on a git commit. Thanks for the patience.

**Comment by deansheather** [comment]
Thank you for this PR. :smiley:

**Comment by deansheather** [comment]
@eargollo Could you reopen your changes on PR #118 for Windows support?

**Pull request merged**
